### ISSUE TITLE
Add new badge (WeDigBio 2021)

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notes-from-nature-field-book#121]
**Is your feature request related to a problem? Please describe.**
This is a feature request for the Notes from Nature Field Book.

**Describe the solution you'd like**
We want a users to earn a WeDigBio 2021 badge when they make 10 classification between April 8-11 and October 14 - 17, 2021. 

**Describe alternatives you've considered**
I believe we used 10 classifications for the previous WeDigBio badge and we want similar behavior this time. 

**Additional context**
I am in the process of updating the graphic and will attach it here very soon. I just wanted to get the issue in the queue so that it can be scheduled before the event April 8th.

**Comment by mcbouslog** [comment]
Will be similar to #108

**Comment by denslowm** [comment]
Here is the updated badge for 2021. 

![WeDigBio_Badge_2021](https://user-images.githubusercontent.com/2152565/113298220-d465a100-92b8-11eb-9d02-5905eb7a78c0.png)
